# Model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
torch_dtype: bfloat16

# Hyperparameters
learning_rate: 2.0e-5
gradient_checkpointing: true
num_train_epochs: 1.0
logging_steps: 1
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
max_length: 8192
warmup_ratio: 0.03
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
output_dir: Result/Qwen-1.5B_SFT
report_to:
- wandb
seed: 42